name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '00 7 * * *'
#   push:
#     branches: [ "develop" ]
#     # Publish semver tags as releases.
#     tags: [ 'v*.*.*' ]
#   pull_request:
#     branches: [ "develop" ]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  
  # Use ESnet Registry
  #ESNET_REGISTRY: wharf.es.net
  
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

# Sign containers using cosign
  SIGN: false

  # Set this to false to skip tests
  RUN_TESTS: false  


jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check_activity.outputs.has_changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.QN_RO_PAT }}
          ref: develop
          fetch-depth: 0

      - name: Check for recent branch activity
        id: check_activity
        run: |
          COMMIT_COUNT=$(git rev-list --count --since="24 hours ago" HEAD)
          if [ "$COMMIT_COUNT" -gt 0 ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Activity found on the 'develop' branch in the last 24 hours ($COMMIT_COUNT commits). Proceeding with the build."
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No new commits pushed to the 'develop' branch in the last 24 hours. Build will be skipped."
          fi
  build:
    # This job depends on the check-for-changes job.
    needs: check-for-changes
    # It runs only if changes were found OR if the workflow was manually dispatched.
    if: needs.check-for-changes.outputs.has_changes == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 50 
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    outputs:
        tags: ${{ steps.meta.outputs.tags }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.QN_RO_PAT }}
          ref: develop

      - name: Debug repository and branch info
        run: |
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
          echo "GITHUB_REF = $GITHUB_REF"
          echo "Listing remote branches:"
          git branch -a
          echo "Remote heads:"
          git ls-remote origin

      # - name: Set up SSH with github
      #   uses: MrSquaare/ssh-setup-action@2d028b70b5e397cf8314c6eaea229a6c3e34977a # v3.1.0
      #   with:
      #     host: github.com
      #     private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     private-key-name: github-ppk    

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request' && env.RUN_TESTS == 'true'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # Set up multiple platforms with QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      # - name: Log into registry Docker Hub
      #   if: github.event_name != 'pull_request' && env.RUN_TESTS == 'true'
      #   uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # - name: Log into registry ${{ env.REGISTRY }}
      #   if: github.event_name != 'pull_request'
      #   uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: Log into registry ${{ env.ESNET_REGISTRY }}
      #   if: github.event_name != 'pull_request' && env.RUN_TESTS == 'true'
      #   uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      #   with:
      #     registry: ${{ env.ESNET_REGISTRY }}
      #     username: ${{ secrets.ESNET_USERNAME }}
      #     password: ${{ secrets.ESNET_PASSWORD }}
      #   continue-on-error: true

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=develop

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        #docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: docker/Dockerfile
          #ssh: default
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          secrets: |
            GH_TOKEN=${{ secrets.QN_RO_PAT }}

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: github.event_name != 'pull_request' && env.SIGN == 'true'
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
